/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/WawaOffice.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Office(props) {
    const { nodes, materials } = useGLTF('./models/WawaOffice.glb')
    return (
        <group {...props} dispose={null}>
            {/* Main Office */}
            <mesh
                geometry={nodes['01_office'].geometry}
                material={materials['01']}
                castShadow
                receiveShadow
            />

            {/* Library (2nd floor) */}
            <mesh
                geometry={nodes['02_library'].geometry}
                material={materials['02']}
                position={[0, 2.114, -2.23]}
                castShadow
                receiveShadow
            />

            {/* Attic */}
            <mesh
                geometry={nodes['03_attic'].geometry}
                material={materials['03']}
                position={[-1.97, 4.227, -2.199]}
                castShadow
                receiveShadow
            />
        </group>
    )
}

// Preload for better performance
useGLTF.preload('./models/WawaOffice.glb')
