/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/WawaOffice.glb 
*/
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import gsap from 'gsap';
import React, { useLayoutEffect, useRef } from 'react'


export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Office(props) {
    const { nodes, materials } = useGLTF('./models/WawaOffice.glb')

    const ref = useRef();
    const tl = useRef();
    const scroll = useScroll();

    // scroll animation
    useFrame(() => {
        if (tl.current) {
            tl.current.seek(scroll.offset * tl.current.duration())
        }
    })

    useLayoutEffect(() => {
        tl.current = gsap.timeline()

        // vertical animation
        tl.current.to(
            ref.current.position,
            {
                duration: NB_FLOORS,
                y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
            },
            0
        )
    }, [])

    return (
        <group {...props} dispose={null} ref={ref}>
            {/* Main Office */}
            <mesh
                geometry={nodes['01_office'].geometry}
                material={materials['01']}
                castShadow
                receiveShadow
            />

            {/* Library (2nd floor) */}
            <mesh
                geometry={nodes['02_library'].geometry}
                material={materials['02']}
                position={[0, 2.114, -2.23]}
                castShadow
                receiveShadow
            />

            {/* Attic */}
            <mesh
                geometry={nodes['03_attic'].geometry}
                material={materials['03']}
                position={[-1.97, 4.227, -2.199]}
                castShadow
                receiveShadow
            />
        </group>
    )
}

// Preload for better performance
useGLTF.preload('./models/WawaOffice.glb')
